name: Grizzly
options:
  bundleIdPrefix: com.grizzly
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.0

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.9
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: Grizzly

targets:
  Grizzly-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/Grizzly
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: ZIPFoundation
    settings:
      base:
        PRODUCT_NAME: Grizzly
        PRODUCT_BUNDLE_IDENTIFIER: com.grizzly.ZipViewer
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SUPPORTS_MACCATALYST: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        INFOPLIST_KEY_LSSupportsOpeningDocumentsInPlace: YES
        INFOPLIST_KEY_UISupportsDocumentBrowser: YES
        # Document types - support opening ZIP files
        INFOPLIST_KEY_CFBundleDocumentTypes: |
          <array>
            <dict>
              <key>CFBundleTypeExtensions</key>
              <array>
                <string>zip</string>
              </array>
              <key>CFBundleTypeName</key>
              <string>ZIP Archive</string>
              <key>CFBundleTypeRole</key>
              <string>Viewer</string>
              <key>LSHandlerRank</key>
              <string>Owner</string>
              <key>LSItemContentTypes</key>
              <array>
                <string>public.zip-archive</string>
              </array>
            </dict>
          </array>

  Grizzly-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/Grizzly
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: ZIPFoundation
    settings:
      base:
        PRODUCT_NAME: Grizzly
        PRODUCT_BUNDLE_IDENTIFIER: com.grizzly.ZipViewer
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024 Grizzly. All rights reserved."
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_PREVIEWS: YES
        CODE_SIGN_ENTITLEMENTS: Grizzly.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        # Document types - support opening ZIP files
        INFOPLIST_KEY_CFBundleDocumentTypes: |
          <array>
            <dict>
              <key>CFBundleTypeExtensions</key>
              <array>
                <string>zip</string>
              </array>
              <key>CFBundleTypeName</key>
              <string>ZIP Archive</string>
              <key>CFBundleTypeRole</key>
              <string>Viewer</string>
              <key>LSHandlerRank</key>
              <string>Owner</string>
              <key>LSItemContentTypes</key>
              <array>
                <string>public.zip-archive</string>
              </array>
            </dict>
          </array>
